// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupExperimentPrefs.dom.push.alwaysConnect", true);
user_pref("app.normandy.user_id", "d716ff98-72ff-48ce-bd68-ed04d0f523d8");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1543753815);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1543753935);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1543753335);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1543753575);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1543753455);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1543753695);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1543754175);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1543754055);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 368640);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1543753305);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 74);
user_pref("browser.newtabpage.activity-stream.impressionId", "{fbc05a76-555e-44dc-89fb-753fca956c09}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1543705200);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.onboarding.seen-tourset-version", 2);
user_pref("browser.onboarding.tour-type", "new");
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1543753380676");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1543755151676");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1543753323250");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1543756923250");
user_pref("browser.search.region", "ES");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1543753330");
user_pref("browser.slowStartup.averageTime", 12365);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20181116153855");
user_pref("browser.startup.homepage_override.mstone", "63.0.3");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":14,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 3);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1543753317850");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "63.0.3");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "1a80f55044244f808c063b8479dd2e04");
user_pref("extensions.blocklist.lastModified", "Mon, 26 Nov 2018 14:19:56 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 27);
user_pref("extensions.getAddons.cache.lastUpdate", 1543753817);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "63.0.3");
user_pref("extensions.lastPlatformVersion", "63.0.3");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"directory\":\"{26e105c6-357f-4921-a794-00c4028563ce}\",\"addons\":{\"fxmonitor@mozilla.org\":{\"version\":\"2.8\"}}}");
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"4fce644d-c86b-48f3-a6be-fc946b6db74a\",\"webcompat@mozilla.org\":\"b68342e4-48fb-4348-8c66-a623461c4fc8\",\"screenshots@mozilla.org\":\"e00cc8f1-df0c-4343-9e2d-4d00f4e4822d\",\"fxmonitor@mozilla.org\":\"ad500cf4-d767-4697-87ee-d8255ce7d57d\"}");
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1543753818);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20181116153855");
user_pref("media.gmp-manager.lastCheck", 1543753833);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 103697);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "d96897fb-3965-40e0-b7bb-d6abdfc16753");
user_pref("services.blocklist.addons.checked", 1543606976);
user_pref("services.blocklist.gfx.checked", 1543606976);
user_pref("services.blocklist.onecrl.checked", 1543606976);
user_pref("services.blocklist.pinning.checked", 1543606976);
user_pref("services.blocklist.plugins.checked", 1543606976);
user_pref("services.settings.clock_skew_seconds", 146719);
user_pref("services.settings.last_etag", "\"1543241996691\"");
user_pref("services.settings.last_update_seconds", 1543606976);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1543753299);
user_pref("toolkit.telemetry.cachedClientID", "db06272a-608e-4478-9b29-4ea8c08e9a5b");
user_pref("toolkit.telemetry.previousBuildID", "20181116153855");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
